version: '3'
services:
  prestashop:
    image: prestashop/prestashop
    container_name: prestashop
    restart: always
    enviorments:
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASSWD=admin
      - PS_INSTALL_DB=1
    ports:
      - 8080:80
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin


