---
- name: Install installs
  apt:
    name: 
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: latest

- name: test
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu   focal stable
    state: present

- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-pip

- name: Install docker python module
  pip:
    name: docker==5.0.0
